## Basic setup 
#-----------------------
# CRDS settings
crds_path: "/home/zpscofield/crds_cache"
crds_server_url: "https://jwst-crds.stsci.edu"

dir_prefix: "uncal_test"

combine_observations: false # Whether to combine all uncal files into one mosaic (per filter). Note that these observations should be of the same region,
                            # of course. If false, the pipeline will run on each independent observation based on their IDs and create output
                            # directories based on the observation names.

custom_name: "Combined_observation" # Custom association name to use when combining all observations. 
group_by_directory: true # Set this option to true if you want to run the pipeline for observations per UNCAL directory. It
                         # will override combine_observations, and create mosaic images for each UNCAL directory. The output directories will be
                         # labeled according to the initial UNCAL directory names.
#-----------------------

## Stage 1 settings
#-----------------------
stage1_nproc: 20 # Number of processes to use for stage 1 of the pipeline. Note that this and all other stages and calibration steps, the number of 
                 # processes will be reduced if the number of files is less than the user-specified nproc value.
ramp_fit_cores: "1" # Currently (as of 24.11.21) it is necessary to get the development version of the stcal repo (> pip install git+https://github.com/spacetelescope/stcal).
                    # to use more than a single core. However, we strongly advise against this because there is currently a visual artifact associated with using >1 cores 
                    # for the ramp_fitting step.
jump_cores: "1"
#-----------------------

## 1/f noise correction settings
#-----------------------
fnoise_nproc: 10
#-----------------------

## Stage 2 settings 
#-----------------------
stage2_nproc: 10
skip_resample: "true"
#-----------------------

## Wisp removal settings
#-----------------------
wisp_nproc: 10
plot_sky: false
#-----------------------

## Background subtraction settings
#-----------------------
bkg_nproc: 10
#----------------------- 

## Stage 3 settings ##
#-----------------------
# Resample settings
pixel_scale: 0.02
pixfrac: 0.75
rotation: 0.0
res_kernel: "square"

# Tweakreg settings
external_reference: false
reference_path: ""
starfinder: "dao"
tweakreg_snr: 7.0
#-----------------------

## Steps to skip ##
#----------------------- 
# Uncomment skip_steps and steps to skip below if necessary.
skip_steps:
  # - download_uncal_references
  # - stage1
  # - fnoise_correction
  # - download_rate_references
  # - stage2
  # - wisp_subtraction
  # - background_subtraction
  # - download_cal_references
  # - stage3
#-----------------------
