crds_path: /home/zpscofield/crds_cache
crds_server_url: https://jwst-crds.stsci.edu
pipeline_directory: .
data_directory: /Volumes/YOUNG6/JWST_pipeline_dev/A209data_f444w
output_directory: .
combine_observations: true
custom_name: Combined_Observation
group_by_directory: false
stage1_nproc: 8
ramp_fit_cores: '1'
jump_cores: '1'
stage2_nproc: 8
skip_resample: true
wisp_directory: /Volumes/YOUNG6/kyle_pipeline/wisp-templates/version4
wisp_nproc: 8
plot_sky: false
cfnoise_nproc: 8
bkg_nproc: 8
stage3_use_multiprocessing: false
min_processes: 8
outlier_in_memory: true
pixel_scale: 0.02
pixfrac: 0.75
rotation: 0.0
res_kernel: square
resample_in_memory: true
external_reference: GAIADR3
starfinder: segmentation
snr_threshold: 5.0
abs_fitgeometry: rshift
fitgeometry: rshift
skymethod: match
extract_sci: true
extract_err: true
extract_con: false
extract_wht: true
extract_var_poisson: false
extract_var_rnoise: false
extract_var_flat: false
skip_steps: []
color_image_enabled: false
color_image_min_level: 0.001
color_image_max_quantile: 0.99999
color_image_gamma: 2.2
color_image_filter_hues: {}
