crds_path: /home/zpscofield/crds_cache
crds_server_url: https://jwst-crds.stsci.edu
pipeline_directory: .
data_directory: /Volumes/YOUNG6/JWST_pipeline_dev/A68_all_data
output_directory: .
combine_observations: true
custom_name: A68_all_test
group_by_directory: false
stage1_nproc: 75
ramp_fit_cores: '1'
jump_cores: '1'
stage2_nproc: 75
skip_resample: true
wisp_directory: /Volumes/YOUNG6/kyle_pipeline/wisp-templates/version4
wisp_nproc: 75
plot_sky: false
cfnoise_nproc: 75
bkg_nproc: 75
stage3_use_multiprocessing: true
min_processes: 3
outlier_in_memory: true
pixel_scale: 0.02
pixfrac: 0.75
rotation: 0.0
res_kernel: square
resample_in_memory: true
external_reference: GAIADR3
starfinder: segmentation
snr_threshold: 5.0
abs_fitgeometry: rshift
fitgeometry: rshift
skymethod: match
extract_sci: true
extract_err: true
extract_con: false
extract_wht: true
extract_var_poisson: false
extract_var_rnoise: false
extract_var_flat: false
skip_steps:
- download_uncal_references
- stage1
- download_rate_references
- stage2
- wisp_subtraction
- cal_fnoise_reduction
- background_subtraction
- download_cal_references
- stage3
color_image_enabled: true
color_image_min_level: 0.001
color_image_max_quantile: 0.9999
color_image_gamma: 2.2
color_image_subtract_sky: true
color_image_filter_hues:
  F090W: 240.0
  F200W: 164.57142857142858
  F277W: 111.08571428571432
  F356W: 56.91428571428573
  F115W: 222.85714285714286
  F150W: 198.85714285714286
  F210M: 157.71428571428572
  F300M: 96.0
  F410M: 21.942857142857164
  F444W: 0.0
